**Numpy Dizi İşlemeleri**

In [26]:

import numpy as np #numpy kütüphanesini np takma adı ile projeye dahil ediyoruz

In [6]:
dizi=np.full((4,3),5)
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
#yeni bir numpy dizisi oluşturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [14]:
#oluşturduğumuz diziyi bir değişkene aktarıyoruz
dizi=np.array(["elma","erik","iğde"])

In [19]:
dizi

array([1.  , 2.  , 3.14])

In [ ]:
dizi=np.array([1.2.3])

In [16]:
dizi=np.array([1,2,3.14])

In [18]:
dizi.dtype #dizi değişken türünü verir.numpy dizelerinde elemanların hepsi aynı ttürdedir

dtype('float64')

In [ ]:
dizi=np.array([1,2,3.14],dtype=int)

**numpy ile farklı boyutlarda dizi oluşturma**

In [30]:
#bir boyutlu dizi oluşturma 
birboyut=np.array([1,2,3,4])
#iki boyutlu dizi oluşturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [31]:
birboyut

array([1, 2, 3, 4])

In [32]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**numpy yer tutucular**

In [33]:
np.zeros(7) #7 sıfırdan oluşan tek boyutlu dizi oluşturur

array([0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((2,3),dtype=int) #* sıfırdan oluşan 2 boyutlu int dizi oluşturur

array([[0, 0, 0],
       [0, 0, 0]])