In [9]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [10]:
a=np.array([1,2,3])
dizi=np.array([1,2,3,3.14])
dizi

array([1.  , 2.  , 3.  , 3.14])

In [11]:
dizi=np.array([1,2,3,3.14],dtype=int)
dizi

array([1, 2, 3, 3])

In [12]:
birboyut=np.array([1,2,3])
birboyut


array([1, 2, 3])

In [13]:
ikiboyut = np.array([[1,2,3], [4,5,6]])
ikiboyut


array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.zeros(5)
np.zeros(5)
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
np.ones(5)
np.ones((4,3))
np.ones((4,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])